export const nameClassMarcacao = 'marcacao'
export const nameClassMarcacaoOculta = 'marcacoes-ocultas'
export const nameClassRectFormat = 'formato-retangular'
export const nameClassOvalFormat = 'formato-oval'
export const nameClassSelecionada = 'selecionada'